In [ ]:
import csv
import types
file=open('/spreedsheet marks - Sheet1.csv','r')
data=list(csv.reader(file,delimiter=","))
file.close()
print(data)
print(type(data))
print(data[0])

[['roll no.', 'marks'], ['1', '91'], ['2', '54'], ['3', '66'], ['4', '62'], ['5', '89'], ['6', '85'], ['7', '45'], ['8', '55'], ['9', '78'], ['10', '71']]
<class 'list'>
['roll no.', 'marks']


In [ ]:
print(data[1][2])

22


In [ ]:
print(data[0])

['id', 'name', 'age', 'occ']


In [ ]:
print(data[1][3])

engineer


In [ ]:
print(data[1][2])+data[3][2])

2224


In [ ]:
print(data)
int(data[1][2])+int(data[3][2])

[['id', 'name', 'age', 'occ'], ['1', 'Vinay', '22', 'engineer'], ['2', 'Kushal ', '25', 'doctor'], ['3', 'Aman', '24', 'accountant ']]


46

In [ ]:
sum=0
for i in range(1,len(data)):
  sum=int(data[1][2])+int(data[3][2])
print('the sum of age is',sum)

the sum of age is 46


In [ ]:
sum=0
for i in range(1,len(data)):
  sum=int(sum)+int(data[3][2])
print('the sum of age is',sum)

the sum of age is 72


In [ ]:
file=open('/Untitled spreadsheet - Sheet1 (5) - Copy.csv','r')
data1=list(csv.reader(file,delimiter=','))
file.close()
print(data)
data1=data
data1+data

[['id', 'name', 'age', 'occ'], ['1', 'Vinay', '22', 'engineer'], ['2', 'Kushal ', '25', 'doctor'], ['3', 'Aman', '24', 'accountant ']]


[['id', 'name', 'age', 'occ'],
 ['1', 'Vinay', '22', 'engineer'],
 ['2', 'Kushal ', '25', 'doctor'],
 ['3', 'Aman', '24', 'accountant '],
 ['id', 'name', 'age', 'occ'],
 ['1', 'Vinay', '22', 'engineer'],
 ['2', 'Kushal ', '25', 'doctor'],
 ['3', 'Aman', '24', 'accountant ']]

In [ ]:
mylist=[]
mylist.append(data[1])
mylist[0].insert(3,data[1][2])
print(mylist)

[['1', 'Vinay', '22', '22', 'engineer']]


In [ ]:
mylist=[]
for i in range(10):
  mylist.append(data[i]+data2[i])
print(mylist)

[['emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3']]
<class 'list'>
['emplyoee id', 'Name', 'salary', 'experience']


In [ ]:
import csv
import types
mylist=[]
file=open('/content/es2.csv','r')
data2=list(csv.reader(file,delimiter=","))
file.close()
print(data2)
print(type(data2))
print(data2[0])

[['name', 'salary', 'experince'], ['yash ', '50000', '3'], ['rohit ', '45000', '2.5'], ['vedant', '60000', '2'], ['avdut', '55000', '2.5']]
<class 'list'>
['name', 'salary', 'experince']


In [ ]:
import csv
mylist=[]
file=open('/content/es.csv','r')
data=list(csv.reader(file,delimiter=","))
file.close()
print(data)
print(type(data))
print(data[0])

[['emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3']]
<class 'list'>
['emplyoee id', 'Name', 'salary', 'experience']


In [ ]:
import csv
mylist=[]
file=open('/content/es.csv','r')
data2=list(csv.reader(file,delimiter=","))
file.close()
print(data2)
print(type(data2))
print(data2[0])

[['emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3']]
<class 'list'>
['emplyoee id', 'Name', 'salary', 'experience']


In [ ]:
mylist=[]
for i in range(len(data2)):
  mylist.append(data[i]+data2[i])
print(mylist)



[['emplyoee id', 'Name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2', '201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5', '202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3', '203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5', '204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3', '205', 'harsh', '47000', '3']]


In [ ]:
for i in range(len(data)):
  data[i].extend(data2[i])
print(data)

[['emplyoee id', 'Name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2', '201', 'niraj', '40000', '2', '201', 'niraj', '40000', '2', '201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5', '202', 'vinit', '45000', '2.5', '202', 'vinit', '45000', '2.5', '202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3', '203', 'anuj', '50000', '3', '203', 'anuj', '50000', '3', '203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5', '204', 'nirmal', '42000', '2.5', '204', 'nirmal', '42000', '2.5', '204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3', '205', 'harsh', '47000', '3', '205', 'harsh', '47000', '3', '205', 'harsh', '47000', '3']]


In [ ]:
import csv
import types
mylist=[]
file=open('/Untitled spreadsheet - Sheet1 (12).csv','r')
data2=list(csv.reader(file,delimiter=","))
file.close()
print(data2)
print(type(data2))
print(data2[0])


[['emplyoee id', 'Name', 'salary', 'experience'], ['201', 'niraj', '40000', '2'], ['202', 'vinit', '45000', '2.5'], ['203', 'anuj', '50000', '3'], ['204', 'nirmal', '42000', '2.5'], ['205', 'harsh', '47000', '3']]
<class 'list'>
['emplyoee id', 'Name', 'salary', 'experience']


In [ ]:
import csv
mylist=[]
file=open('/Untitled spreadsheet - Sheet1 (13).csv','r')
data=list(csv.reader(file,delimiter=","))
file.close()
print(data)
print(type(data))
print(data[0])

[['empolye id', 'name', 'salary', 'experience'], ['201', 'harshwardhan', '250000', '2'], ['202', 'vedant', '300000', '3'], ['203', 'rishab', '200000', '1'], ['204', 'rohit', '500000', '3'], ['205', 'avdut', '400000', '4']]
<class 'list'>
['empolye id', 'name', 'salary', 'experience']


In [ ]:
mylist=[]
for i in range(len(data2)):
  mylist.append(data[i]+data2[i])
print(mylist)

[['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience'], ['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2'], ['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5'], ['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3'], ['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5'], ['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3']]


In [ ]:
for i in range(len(data)):
  data[i].extend(data2[i])
print(data)

[['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience'], ['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2'], ['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5'], ['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3'], ['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5'], ['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3']]


In [ ]:
sal=[]
for i in range(len(mylist)):
  sal.append(int(mylist[1][2]))
print("addition of sal is",max(sal))

addition of sal is 250000


In [ ]:
l=len(mylist)
sal=[]
for i in range(1,l):
  sal.append(int(mylist[i][2]))
print("maximum sal is",max(sal))

maximum sal is 500000


In [ ]:
print(min(sal))
print("minimum sal is",min(sal))

200000
minimum sal is 200000


In [ ]:
m=sum(sal)/len(sal)
avg=round(m,9)
print(avg)
print('the average salary is=',avg)

330000.0
the average salary is= 330000.0


In [ ]:
#x is the name of the function
x=lambda a:a+10
y=lambda b:b+20
print(x(2))
print(y(2))



12
22


In [ ]:
#x is the name of the function
x=lambda a:a*10
y=lambda b:b*20
print(x(2))
print(y(2))


20
40


In [ ]:
#sort the merged list based on name
mylist.sort(key=lambda x:x[0])
print(mylist)

[['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2'], ['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5'], ['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3'], ['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5'], ['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3'], ['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience']]


In [ ]:
mylist.sort(key=lambda x:x[1])
print(mylist)

[['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3'], ['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2'], ['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience'], ['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3'], ['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5'], ['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5']]


In [ ]:
print("the previous list is")
for i in mylist:
  print(i)
print("the sorted list is")
mylist.sort(key=lambda x:x[0])
for i in mylist:
  print(i)


the previous list is
['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3']
['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2']
['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5']
['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5']
['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3']
['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience']
the sorted list is
['201', 'harshwardhan', '250000', '2', '201', 'niraj', '40000', '2']
['202', 'vedant', '300000', '3', '202', 'vinit', '45000', '2.5']
['203', 'rishab', '200000', '1', '203', 'anuj', '50000', '3']
['204', 'rohit', '500000', '3', '204', 'nirmal', '42000', '2.5']
['205', 'avdut', '400000', '4', '205', 'harsh', '47000', '3']
['empolye id', 'name', 'salary', 'experience', 'emplyoee id', 'Name', 'salary', 'experience']


In [ ]:
#sort the merged list based on salary
mylist.sort(key=lambda x: int(x[1]))
for i in mylist:
    print(i)

ValueError: ignored

In [ ]:
import csv
import types
file=open('/content/employe.csv','r')
data=list(csv.reader(file,delimiter=","))
file.close()
print(data)
print(type(data))
print(data)

[['Sr. No.', 'Employee name ', "Employee I'D", 'Age ', 'Date Of birth'], ['1', 'Juber Maindarge', '2.02201E+11', '23', '11/1/2004'], ['2', 'Shruti Garad ', '2.02201E+11', '26', '11/2/2004'], ['3', 'Yash Kumbhar', '2.02201E+11', '28', '11/3/2004'], ['4', 'Swastik Paratkar', '2.02201E+11', '25', '11/4/2004'], ['5', 'Ashraf Shaikh', '2.02201E+11', '21', '11/5/2004'], ['6', 'Bhagyashree Thakur', '2.02201E+11', '29', '11/6/2004'], ['7', 'Hitarth Paliwal', '2.02201E+11', '28', '11/7/2004'], ['8', 'Vaibhav ', '2.02201E+11', '32', '11/8/2004'], ['9', 'Ramani Vemula ', '2.02201E+11', '26', '11/9/2004'], ['10', 'Neil Desai', '2.02201E+11', '24', '11/10/2004'], ['11', 'Gandharva Jhadav ', '2.02201E+12', '29', '11/11/2004'], ['12', 'Shalom Jadhav ', '2.02201E+12', '25', '11/12/2004'], ['13', 'Prathemesh Chavan ', '2.02201E+12', '33', '11/13/2004'], ['14', 'Harashada Thorat', '2.02201E+11', '30', '11/14/2004'], ['15', 'Om Dhakne ', '2.02201E+11', '33', '11/15/2004'], ['16', 'Vaishanvi Mirje ', '2.0

In [ ]:
dict1={"name":"yash","div":"d","age":18}
print(dict1)
print(type(dict1))
print(len(dict1))


{'name': 'yash', 'div': 'd', 'age': 18}
<class 'dict'>
3


In [ ]:
dict2=dict(name="vedant",div="c",age=19)
x=dict2.items()
print(x)
k=dict2.keys()
v=dict2.values()

dict_items([('name', 'vedant'), ('div', 'c'), ('age', 19)])


In [ ]:
dict1["gender"]="male"

In [ ]:
x1=dict1["name"]
print(x1)

yash


In [ ]:
x2=dict2["age"]
print(x2)

19


In [ ]:
dict1.update{"book":"good habits":"writer":"hyden"}
print(dict1)

SyntaxError: ignored

In [ ]:
dict1={"name":"good habits","price":275,"pages":249}
dict2={"author_name":"hyden"}
dict1.update(dict2)
print(dict1)
x=dict1["pages"]
print(x)
a=dict1.keys()
print(a)
print(type(a))
b=dict1.items()
print(b)
print(type(b))
dict1.pop("name")
print(dict1)
dict1.popitem()
print(dict1)

{'name': 'good habits', 'price': 275, 'pages': 249, 'author_name': 'hyden'}
249
dict_keys(['name', 'price', 'pages', 'author_name'])
<class 'dict_keys'>
dict_items([('name', 'good habits'), ('price', 275), ('pages', 249), ('author_name', 'hyden')])
<class 'dict_items'>
{'price': 275, 'pages': 249, 'author_name': 'hyden'}
{'price': 275, 'pages': 249}


In [ ]:
 #tupple
t=("mango",44,"name",421)
print(t)
print(t[0])
print(t[-1])
print(t[-2])
print(t[2])
print(t[2:])
print(t[:2])
print(len(t))
print(type(t))
b=input("enter a fruit name")
for i in t :
  if b=="apple":
    print("fruit is present")
    break


('mango', 44, 'name', 421)
mango
421
name
name
('name', 421)
('mango', 44)
4
<class 'tuple'>
enter a fruit nameapple
fruit is present


In [ ]:
t=("apple","grapes")
list1=list(t)
list1.append("banana")
t=tuple(list1)
print(t)
list1=list(t)
list1.remove("apple")
t=tuple(list1)
print(list)

('apple', 'grapes', 'banana')
<class 'list'>


In [ ]:
import csv
import types
file2=open('/content/Sales (1).csv','r')
file1=open('/content/Sales (1).csv','r')
data=list(csv.reader(file2,delimiter=","))
data2=list(csv.reader(file1,delimiter=","))
l=len(data)
informationdata=[]
for i in range(0,l,1):
  informationdata.append(data[i][1])
for i in  informationdata:
   print(i)
print("-----------------------------------------------------------------------------------------------")
for i in data2:
  print(i)
  data_customer=[]
  data_gender=[]
for i in range(0,l,1):
  data_customer.append(listdata[i][3])
for i in range(0,l,1):
  data_gender.append(listdata[i][4])
  list=[]
  print("name")
for i in data_customer:



Product details
Lenovo Laptop
Samsung M31
Realmi 10pro
Oppo F21
Lenovo Laptop
Samsung M31
LG TV 32"
Oppo F21
Lenovo Laptop
Samsung M31
LG TV 32"
Lenovo Laptop
Samsung M31
Realmi 10pro
Lenovo Laptop
Oppo F21
LG TV 32"
Lenovo Laptop
Samsung M31
LG TV 32"
-----------------------------------------------------------------------------------------------
['Product ID', 'Product details', 'Supplier Details', 'Customer Details', 'Gender']
['P00001', 'Lenovo Laptop', 'Raka Ele.', 'Kaustubh Mahajan', 'Male']
['P00002', 'Samsung M31', 'Vijay Sales', 'Siddhi Kiwale', 'Female']
['P00003', 'Realmi 10pro', 'Gada Ele.', 'Sanket Kandalkar', 'Male']
['P00004', 'Oppo F21', 'Surya Ele.', 'Yash Mali', 'Male']
['P00005', 'Lenovo Laptop', 'Raka Ele.', 'Yash Bagul', 'Male']
['P00006', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female']
['P00007', 'LG TV 32"', 'Vijay Sales', 'Sanket Kandalkar', 'Male']
['P00008', 'Oppo F21', 'Surya Ele.', 'Kaustubh Mahajan', 'Male']
['P00009', 'Lenovo Laptop', 'Raka Ele.', 'Y

NameError: ignored

In [ ]:
dict1={"book id":201,"book name":"stephan hawking"}
dict2={"price":2000}
dict1.update(dict2)
print(dict1)
list1='stephan hawking'
s=[i for i in range(1,10)  if i%2==0 ]
print(s)


{'book id': 201, 'book name': 'stephan hawking', 'price': 2000}
[6, 8]


In [ ]:
dict1={"book id":201,"book name":"stephan hawking"}
dict2={"price":2000}
dict1.update(dict2)
print(dict1)
list1='stephan hawking'
s=["mango" if i%2==0 else "orange" for i in range(1,10)]
print(s)

{'book id': 201, 'book name': 'stephan hawking', 'price': 2000}
['orange', 'mango', 'orange', 'mango', 'orange', 'mango', 'orange', 'mango', 'orange']


In [ ]:
import csv
file=open('/Untitled spreadsheet - Sheet1.csv','r')
data1=list(csv.reader(file,delimiter=','))
print(data1)
supp=[]
cust=()
pro={}
t1=[]
t2=[]

[['id', 'product name', 'product details', 'product quantity', 'p amount'], ['A101', 'Lenovo', 'laptop', '3', '550000'], ['A102', 'dell', 'laptop', '2', '600000'], ['A103', 'HP', 'laptop', '3', '450000'], ['A104', 'macbook', 'laptop', '5', '900000'], ['A105', 'ramsung', 'TV', '4', '400000'], ['A106', 'Apple', 'smartphone', '10', '700000'], ['A107', 'vivo', 'smartphone', '6', '250000'], ['A108', 'mi', 'tabs', '10', '300000'], ['A109', 'Lenovo ', 'smartphone', '5', '120000']]


In [ ]:
import csv

f1 = open("/content/sample_data/Sales.csv","r")
data = list(csv.reader(f1))

CNm = []; CGender = [] ; CCity = []; #List declaration to store Customer Details
Product = {}   #Dictionary Declaration to store product Details
SNm = () ; SCity = () #Tuple to stire suppiler details
l1 = []; l2 = []

for i in range(1,len(data)):
    pd = []
    print(data[i])
    CNm.append(data[i][0])
    CGender.append(data[i][1])
    CCity.append(data[i][2])
    pd.append(data[i][4])
    pd.append(data[i][5])
    pd.append(data[i][8])
    pd.append(data[i][9])
    print(pd)
    Product [data[i][3]] =  pd
    l1.append(data[i][6])
    l2.append(data[i][7])


SNm = tuple(l1)
SCity = tuple(l2)

FileNotFoundError: ignored

In [ ]:
import csv
file=open('/content/Sales2 (1).csv','r')
data1=list(csv.reader(file,delimiter=','))
print(data1)

[['Product ID', 'Product details', 'Supplier Details', 'Customer Details', 'Gender', 'quantity', 'Pamount'], ['P00001', 'Lenovo Laptop', 'Raka Ele.', 'Kaustubh Mahajan', 'Male', '1', '10000'], ['P00002', 'Samsung M31', 'Vijay Sales', 'Siddhi Kiwale', 'Female', '5', '34567'], ['P00003', 'Realmi 10pro', 'Gada Ele.', 'Sanket Kandalkar', 'Male', '7', '23000'], ['P00004', 'Oppo F21', 'Surya Ele.', 'Yash Mali', 'Male', '9', '45000'], ['P00005', 'Lenovo Laptop', 'Raka Ele.', 'Yash Bagul', 'Male', '4', '29000'], ['P00006', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female', '5', '80000'], ['P00007', 'LG TV 32"', 'Vijay Sales', 'Sanket Kandalkar', 'Male', '6', '56000'], ['P00008', 'Oppo F21', 'Surya Ele.', 'Kaustubh Mahajan', 'Male', '8', '78000'], ['P00009', 'Lenovo Laptop', 'Raka Ele.', 'Yash Mali', 'Male', '3', '96000'], ['P00010', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female', '4', '85000'], ['P00011', 'LG TV 32"', 'Surya Ele.', 'Sanket Kandalkar', 'Male', '2', '56000'], ['P00012

In [ ]:
supp=[]
proqua=[]
cust=()
pro=()
t1=[]
t2=[]
b=len(data1)
cust1=list(cust)
for i in range(1,b,1):
  supp.append(data1[i][2])
  cust1.append(data1[i][3])
  cust1.append(data1[i][4])
  t1.append(data1[i][0])
  t2.append(data1[i][1])
  proqua.append(data1[i][5])
cust=tuple(cust1)
pro=dict(zip(t1,t2))
pro["price"]=10000
s={data1[i][0]:data1[i][1]for i in range(1,len(data1))}
print(supp)
print(cust)
print(pro)
print(pro.keys())
print(s)
print(type(s))
print(proqua)
print(max(proqua))
print('popular products')
for i in range(1,len(data1)):
  if data1[i][5]==max(proqua):
    print(data1[i][1])


['Raka Ele.', 'Vijay Sales', 'Gada Ele.', 'Surya Ele.', 'Raka Ele.', 'Gada Ele.', 'Vijay Sales', 'Surya Ele.', 'Raka Ele.', 'Gada Ele.', 'Surya Ele.', 'Raka Ele.', 'Surya Ele.', 'Raka Ele.', 'Gada Ele.', 'Vijay Sales', 'Deshmukh sales', 'Raka Ele.', 'Deshmukh sales', 'Gada Ele.']
('Kaustubh Mahajan', 'Male', 'Siddhi Kiwale', 'Female', 'Sanket Kandalkar', 'Male', 'Yash Mali', 'Male', 'Yash Bagul', 'Male', 'Siddhi Kiwale', 'Female', 'Sanket Kandalkar', 'Male', 'Kaustubh Mahajan', 'Male', 'Yash Mali', 'Male', 'Siddhi Kiwale', 'Female', 'Sanket Kandalkar', 'Male', 'Kaustubh Mahajan', 'Male', 'Yash Mali', 'Male', 'Siddhi Kiwale', 'Female', 'Tanuja Mali', 'Female', 'Kaustubh Mahajan', 'Male', 'Sanket Kandalkar', 'Male', 'Siddhi Kiwale', 'Female', 'Kaustubh Mahajan', 'Male', 'Yash Mali', 'Male')
{'P00001': 'Lenovo Laptop', 'P00002': 'Samsung M31', 'P00003': 'Realmi 10pro', 'P00004': 'Oppo F21', 'P00005': 'Lenovo Laptop', 'P00006': 'Samsung M31', 'P00007': 'LG TV 32"', 'P00008': 'Oppo F21', 'P

In [ ]:
if

SyntaxError: ignored

In [ ]:
import csv
file=open('/content/Sales2.csv','r')
data1=list(csv.reader(file,delimiter=','))
print(data1)

[['Product ID', 'Product details', 'Supplier Details', 'Customer Details', 'Gender', 'quantity', 'Pamount'], ['P00001', 'Lenovo Laptop', 'Raka Ele.', 'Kaustubh Mahajan', 'Male', '1', '10000'], ['P00002', 'Samsung M31', 'Vijay Sales', 'Siddhi Kiwale', 'Female', '5', '34567'], ['P00003', 'Realmi 10pro', 'Gada Ele.', 'Sanket Kandalkar', 'Male', '7', '23000'], ['P00004', 'Oppo F21', 'Surya Ele.', 'Yash Mali', 'Male', '9', '45000'], ['P00005', 'Lenovo Laptop', 'Raka Ele.', 'Yash Bagul', 'Male', '4', '29000'], ['P00006', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female', '5', '80000'], ['P00007', 'LG TV 32"', 'Vijay Sales', 'Sanket Kandalkar', 'Male', '6', '56000'], ['P00008', 'Oppo F21', 'Surya Ele.', 'Kaustubh Mahajan', 'Male', '8', '78000'], ['P00009', 'Lenovo Laptop', 'Raka Ele.', 'Yash Mali', 'Male', '3', '96000'], ['P00010', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female', '4', '85000'], ['P00011', 'LG TV 32"', 'Surya Ele.', 'Sanket Kandalkar', 'Male', '2', '56000'], ['P00012

In [ ]:
import csv
f1=open("/content/Sales2.csv","r")
data=list(csv.reader(f1))
CName=[];CGender=[];CCity=[]
product={}
SName=();SCity=()
 for i in range(1,len(data)):
 pd=[]
 print(data[i])
 CName.append(data[i][0])
 CGender.append(data[i][1])
 CCity.append(data[i][2])
 pd.append(data[i][4])
 pd.append(data[i][5])
 pd.append(data[i][6])
 print(pd)
product[data[i][3]]=pd

SName=tuple(11)
SCity=tuple(12)
print(CName)
print(CGender)
print(CCity)

for k in product.keys():
print(k,product[k])

print(SName)
print(SCity)

IndentationError: ignored

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a-b)
print(a/b)
r=np.mean(a)
print(r)
r1=np.median(a)
print(r1)
a1=np.copy(a)
print(a1)
print(a1[0])
np.sort(a1)
print(a1)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]
2.0
2.0
[1 2 3]
1
[1 2 3]


In [ ]:
import numpy as np
arr=np.empty((3,2),dtype=int)
print(arr)


[[54648624        0]
 [       0        0]
 [       0        0]]


In [ ]:
import numpy as np
a=np.array([2,3,1])
b=np.array([4,5,6])
c=a+b
print(c)

[6 8 7]


In [ ]:
import numpy as np
a=np.array([2,3,4])
b=np.array([4,9,8])
c=a*b
print(c)

[ 8 27 32]


In [ ]:
import numpy as np
y=np.array([7,5,4])
result=np.mean(y)
print(result)

5.333333333333333


In [ ]:
r1=np.median(y)
print(r1)

5.0


In [ ]:
import numpy as np
q=np.array([1,2,3])
t=np.array([5,4,6])
h=np.array([8,2,3])
f=q+t+h
print(f)

[14  8 12]


In [ ]:
import numpy as np
j=np.array([8,2,1])
print(j)

[8 2 1]


In [ ]:
arr1=np.copy(a)
print(arr1[0])

2


In [ ]:
np.sort(arr1)

array([2, 3, 4])

In [ ]:
z=[[1,2]],[[5,6]]
print(z)

([[1, 2]], [[5, 6]])


In [ ]:
import numpy as np
z=np.array([[1,2],[3,4]])
x=np.array([[5,6],[7,8]])
print(np.add(z,x))

[[ 6  8]
 [10 12]]


In [ ]:
print(np.subtract(z,x))

[[-4 -4]
 [-4 -4]]


In [ ]:
print(np.divide(z,x))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.multiply(z,x))

[[ 5 12]
 [21 32]]


In [ ]:
print(np.sum(a))

9


In [ ]:
#axis=0 is for column

In [ ]:
print(np.sum(z,axis=0))

[4 6]


In [ ]:
print(np.sum(z,axis=1))

[3 7]


In [ ]:
#transpose
print(z,t)

[[1 2]
 [3 4]] [5 4 6]


In [ ]:
import numpy as np
i=np.array([[1,23,3],[3,4,5]])
print(i[1][2])

5


In [ ]:
import numpy as np
a=np.array([1,2]),([4,5])
b=np.array([6,7]),([8,9])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 7  9]
 [12 14]]
[[-5 -5]
 [-4 -4]]


In [ ]:
import numpy as np
f=np.array([[2,5,7],[1,3,5],[3,6,9]])
print(f)
print(np.sum(f,axis=0))

[[2 5 7]
 [1 3 5]
 [3 6 9]]
[ 6 14 21]


In [ ]:
a=np.array([[1,2,10,20,11],[3,4,15,2,10],[10,20,30,40,50],[122,144,134,123,121]])
print(a)
print(np.sum(a,axis=0))

[[  1   2  10  20  11]
 [  3   4  15   2  10]
 [ 10  20  30  40  50]
 [122 144 134 123 121]]
[136 170 189 185 192]


In [ ]:
print(a[3][2:4])

[134 123]


In [ ]:
print(a)

[[  1   2  10  20  11]
 [  3   4  15   2  10]
 [ 10  20  30  40  50]
 [122 144 134 123 121]]


In [ ]:
print(a[:,:])

[[  1   2  10  20  11]
 [  3   4  15   2  10]
 [ 10  20  30  40  50]
 [122 144 134 123 121]]


In [ ]:
print(a[1,1:3])

[ 4 15]


In [ ]:
print(a[1:3,1:3])

[[ 4 15]
 [20 30]]


In [ ]:
print(a[1:4,1:3])

[[  4  15]
 [ 20  30]
 [144 134]]


In [ ]:
print(a[:-1,:2])

[[ 1  2]
 [ 3  4]
 [10 20]]


In [ ]:
np.sort(a)

array([[  1,   2,  10,  11,  20],
       [  2,   3,   4,  10,  15],
       [ 10,  20,  30,  40,  50],
       [121, 122, 123, 134, 144]])

In [ ]:
print(np.sum(a[:,4]))

192


In [ ]:
v=np.array([10,20,30,40,15,35])
print(v[v>20])

[30 40 35]


In [ ]:
import csv
file=open('/content/dataset7.csv','r')
data1=list(csv.reader(file,delimiter=','))
print(data1)

[['team', 'home_wins', 'away_wins', 'home_matches', 'away_matches', 'home_win_percentage', 'away_win_percentage'], ['Rising Pune Supergiant', '5', '5', '8', '8', '62.5', '62.5'], ['Mumbai Indians', '58', '51', '101', '86', '57.42574257', '59.30232558'], ['Chennai Super Kings', '51', '49', '89', '75', '57.30337079', '65.33333333'], ['Delhi Capitals', '3', '7', '6', '10', '50', '70'], ['Sunrisers Hyderabad', '30', '28', '63', '45', '47.61904762', '62.22222222'], ['Rajasthan Royals', '29', '46', '67', '80', '43.28358209', '57.5'], ['Deccan Chargers', '18', '11', '43', '32', '41.86046512', '34.375'], ['Kings XI Punjab', '38', '44', '91', '85', '41.75824176', '51.76470588'], ['Royal Challengers Bangalore', '35', '49', '85', '95', '41.17647059', '51.57894737'], ['Kolkata Knight Riders', '34', '58', '83', '95', '40.96385542', '61.05263158'], ['Delhi Daredevils', '25', '42', '72', '89', '34.72222222', '47.19101124'], ['Pune Warriors', '6', '6', '20', '26', '30', '23.07692308'], ['Kochi Tuskers

In [ ]:
import pandas as pd


data = pd.read_csv('/content/dataset7.csv')


most_home_wins_team = data.loc[data['home_wins'].idxmax(), 'team']
print("Team with the most home wins:", most_home_wins_team)


Team with the most home wins: Mumbai Indians


In [ ]:
average_away_wins = data['away_wins'].mean()
print("Average away wins for all teams:", average_away_wins)


max_home_matches_team = data.loc[data['home_matches'].idxmax(), 'team']
print("Team with the maximum home matches:", max_home_matches_team)


min_home_win_percentage_team = data.loc[data['home_win_percentage'].idxmin(), 'team']
print("Team with the minimum home win percentage:", min_home_win_percentage_team)


Average away wins for all teams: 29.428571428571427
Team with the maximum home matches: Mumbai Indians
Team with the minimum home win percentage: Gujarat Lions


In [ ]:
import numpy as np
i=np.array([[1,2,3],[3,4,15]])

In [ ]:
print(i.max())

15


In [ ]:
print(np.sum(i,axis=0))

[ 4  6 18]


In [ ]:
a=i.argmax()
print(a)

5


In [ ]:
print(i.argmin())

0


In [ ]:
import numpy as np
x=['True']
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
arr3=np.hstack((arr1,arr2))
arr4=np.vstack((arr1,arr2))
arr5=np.column_stack((arr1,arr2))
arr6=np.row_stack((arr1,arr2))
arr7=np.arange(40,200)
arr8=np.arange(-6,-1),(-4,4,2)
print(arr1)

[1 3 5]


In [ ]:
print(arr2)

[2 4 6]


In [ ]:
print(arr3)

[1 3 5 2 4 6]


In [ ]:
print(arr4)

[[1 3 5]
 [2 4 6]]


In [ ]:
print(arr5)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(arr6)

[[1 3 5]
 [2 4 6]]


In [ ]:
print(arr7)

[ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]


In [ ]:
print(arr8)

(array([-6, -5, -4, -3, -2]), (-4, 4, 2))


In [ ]:
import numpy as np
arr9=np.arange(40,45)
print(arr9)
x=[True,False,True,False,True]
arr10=arr9[x]
print(arr10)

[40 41 42 43 44]
[40 42 44]


In [ ]:
arr11=np.array([[11,12,13],[41,21,83],[18,100,201]])
print(arr11)
print(arr11[1][1:2])

[[ 11  12  13]
 [ 41  21  83]
 [ 18 100 201]]
[21]


In [ ]:
print(arr11[1][1:])#slicing

[21 83]


In [ ]:
print(arr11[1][1:3])

[21 83]


In [ ]:
print(arr11[2][1:3])

[100 201]


In [ ]:
print(np.sum(arr11,axis=0))
print(np.min(arr11,axis=0))
print(np.max(arr11,axis=0))
print(np.mean(arr11,axis=0))

[ 70 133 297]
[11 12 13]
[ 41 100 201]
[23.33333333 44.33333333 99.        ]


In [ ]:
print(np.sum(arr11,axis=1))
print(np.min(arr11,axis=1))
print(np.max(arr11,axis=1))
print(np.mean(arr11,axis=1))

[ 36 145 319]
[11 21 18]
[ 13  83 201]
[ 12.          48.33333333 106.33333333]


In [ ]:
np.count_nonzero(arr11==2)


0

In [ ]:
np.count_nonzero(arr11==21)

1

In [ ]:
np.count_nonzero(arr11>4)|(arr11==21)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
np.count_nonzero(arr11<50)

6

In [ ]:
print(np.linalg.matrix_rank(arr11))

3


In [ ]:
print(np.trace(arr11))


233


In [ ]:
print(np.linalg.det(arr11))

-77447.00000000004


In [ ]:
print(np.linalg.inv(arr11))

[[ 0.05266828  0.01435821 -0.00933542]
 [ 0.08711764 -0.02552713  0.00490658]
 [-0.04805867  0.01141426  0.00337005]]


In [1]:
import numpy as np
d1=np.genfromtxt('/content/testmarks1.csv',delimiter=',',dtype=str)
print(d1)
print(type(d1))
print(d1.dtype)

[['RollNo' 'EDS' 'SON' 'DT' 'ET']
 ['801' '43.05' '27.79' '28.7' '27.79']
 ['802' '43.47' '28.52' '28.98' '27.89']
 ['803' '42.24' '28.16' '28.16' '25.63']
 ['804' '39.24' '26.16' '26.16' '26.16']
 ['805' '40.9' '26.03' '27.27' '25.65']
 ['806' '39.47' '26.31' '26.31' '25.21']
 ['807' '41.68' '25.63' '27.79' '25.46']
 ['808' '42.19' '27.61' '28.13' '26.21']
 ['809' '44.75' '28.35' '29.83' '28.21']
 ['810' '46.95' '28.88' '31.3' '28.53']]
<class 'numpy.ndarray'>
<U6


In [3]:
import numpy as np
d1=np.genfromtxt('/content/testmarks2.csv',delimiter=',',dtype=str)
print(d1)
print(type(d1))
print(d1.dtype)

[['RollNo' 'SIC' 'AM' 'FE' 'IC']
 ['801' '28.48' '34.18' '30.56' '22.23']
 ['802' '28.1' '33.72' '30.68' '22.82']
 ['803' '26.16' '31.39' '28.2' '22.53']
 ['804' '26.16' '31.39' '28.78' '20.93']
 ['805' '26.1' '31.32' '28.22' '20.82']
 ['806' '25.45' '30.54' '27.73' '21.05']
 ['807' '26.16' '31.39' '28.01' '20.51']
 ['808' '27.44' '32.93' '28.83' '22.08']
 ['809' '28.63' '34.35' '31.03' '22.68']
 ['810' '30.35' '36.42' '31.38' '23.1']]
<class 'numpy.ndarray'>
<U6


In [4]:
a=d1[1:,0]
print(a)

['801' '802' '803' '804' '805' '806' '807' '808' '809' '810']


In [5]:
b=a.astype('int32')
np.sum(b)
print("the total is",np.sum(b))
np.max(b)
print("the max is",np.max(b))

the total is 8055
the max is 810


In [6]:
print("total records",np.count_nonzero(a))

total records 10


In [10]:
e=d1[1:,4]
print(e)

['22.23' '22.82' '22.53' '20.93' '20.82' '21.05' '20.51' '22.08' '22.68'
 '23.1']


In [11]:
import numpy as np
d1=np.genfromtxt('/content/employees.csv',delimiter=',',dtype=str)
print(d1)
print(type(d1))
print(d1.dtype)

[['EMPLOYEE_ID' 'FIRST_NAME' 'LAST_NAME' 'EMAIL' 'PHONE_NUMBER'
  'HIRE_DATE' 'JOB_ID' 'SALARY' 'COMMISSION_PCT' 'MANAGER_ID'
  'DEPARTMENT_ID']
 ['198' 'Donald' 'OConnell' 'DOCONNEL' '650.507.9833' '21-JUN-07'
  'SH_CLERK' '2600' ' - ' '124' '50']
 ['199' 'Douglas' 'Grant' 'DGRANT' '650.507.9844' '13-JAN-08' 'SH_CLERK'
  '2600' ' - ' '124' '50']
 ['200' 'Jennifer' 'Whalen' 'JWHALEN' '515.123.4444' '17-SEP-03'
  'AD_ASST' '4400' ' - ' '101' '10']
 ['201' 'Michael' 'Hartstein' 'MHARTSTE' '515.123.5555' '17-FEB-04'
  'MK_MAN' '13000' ' - ' '100' '20']
 ['202' 'Pat' 'Fay' 'PFAY' '603.123.6666' '17-AUG-05' 'MK_REP' '6000'
  ' - ' '201' '20']
 ['203' 'Susan' 'Mavris' 'SMAVRIS' '515.123.7777' '07-JUN-02' 'HR_REP'
  '6500' ' - ' '101' '40']
 ['204' 'Hermann' 'Baer' 'HBAER' '515.123.8888' '07-JUN-02' 'PR_REP'
  '10000' ' - ' '101' '70']
 ['205' 'Shelley' 'Higgins' 'SHIGGINS' '515.123.8080' '07-JUN-02'
  'AC_MGR' '12008' ' - ' '101' '110']
 ['206' 'William' 'Gietz' 'WGIETZ' '515.123.8181' '07-J

In [12]:
a=d1[1:,7]
print(a)

['2600' '2600' '4400' '13000' '6000' '6500' '10000' '12008' '8300' '24000'
 '17000' '17000' '9000' '6000' '4800' '4800' '4200' '12008' '9000' '8200'
 '7700' '7800' '6900' '11000' '3100' '2900' '2800' '2600' '2500' '8000'
 '8200' '7900' '6500' '5800' '3200' '2700' '2400' '2200' '3300' '2800'
 '2500' '2100' '3300' '2900' '2400' '2200' '3600' '3200' '2700' '2500']


In [13]:
b=a.astype('int32')
np.max(b)
print("the max salary is",np.max(b))

the max salary is 24000


In [14]:
z=b.argmax()
print(z)

9


In [15]:
z=d1[b.argmax()+1,:]
print(z)

['100' 'Steven' 'King' 'SKING' '515.123.4567' '17-JUN-03' 'AD_PRES'
 '24000' ' - ' ' - ' '90']


In [18]:
j=d1[1:,6]
print(j)

['SH_CLERK' 'SH_CLERK' 'AD_ASST' 'MK_MAN' 'MK_REP' 'HR_REP' 'PR_REP'
 'AC_MGR' 'AC_ACCOUNT' 'AD_PRES' 'AD_VP' 'AD_VP' 'IT_PROG' 'IT_PROG'
 'IT_PROG' 'IT_PROG' 'IT_PROG' 'FI_MGR' 'FI_ACCOUNT' 'FI_ACCOUNT'
 'FI_ACCOUNT' 'FI_ACCOUNT' 'FI_ACCOUNT' 'PU_MAN' 'PU_CLERK' 'PU_CLERK'
 'PU_CLERK' 'PU_CLERK' 'PU_CLERK' 'ST_MAN' 'ST_MAN' 'ST_MAN' 'ST_MAN'
 'ST_MAN' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK'
 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK'
 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK' 'ST_CLERK']


In [23]:
filterarray=(j=="st_clerk")
x=list(filterarray)
clerkdata=arr1[x]
print(clerkdata)

NameError: ignored

In [26]:
r=[]
for i in range(1,len(d1)):
 d1[i][6]=='st_clerk':
 if r.append=('true')
  else:
    r.append=('false')
    print(r)

SyntaxError: ignored